### ISSUE TITLE
Logger for JS files

### ISSUE THREAD

**Issue by Pravinp-egnaroinc** [muuki88/playframework-requirejs-multipage#1]
Hi,

Can you add feature of logging javascript console.err or console.log to the server side log file with appropriate configuration?

**Comment by muuki88** [comment]
First I can recommend you the [angular-require-js-seed](https://github.com/mariussoutier/play-angular-require-seed) activator from Marius. It has a lot more to offer :)

Having said that. Building a logging API should be trivial
1. Define a `LoggingController` which accepts logs, e.g. in `json` format
2. Define a new route e.g. `POST /api/logging controllers.LoggingController.log`
3. Add this route to the `Application` routes
4. Use it 

``` javascript
 jsRoutes.controllers.LoggingController.log();
r.contentType = 'application/json';
r.data = JSON.stringify(data);
$.ajax(r).done(onSuccess).fail(onFail);
```
